"""system

Revision ID: 6a381b8f56e1
Revises: db7e320355f7
Create Date: 2025-03-21 14:12:19.313286+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
from uuid import uuid4
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a381b8f56e1'
down_revision: Union[str, None] = 'db7e320355f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tariffs', ['tariff_name'])

    op.execute("""
        UPDATE public.roles
        SET permission='{"endpoints": ["activate_or_renew_workspace","deactivate_workspace_now",
               "create_new_tariff","get_tariff_by_id","get_list_tariffs",
               "update_exist_tariff","delete_exist_tariff","create_new_tariff_limit",
               "get_tariff_limit_by_id","get_tariff_all_limits_by_tariff_id","update_exist_tariff_limit",
               "delete_exist_tariff_limit","list_users","check_user","block_user","unlock_user"]}'::json
        WHERE role='system';
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tariffs', type_='unique')
    # ### end Alembic commands ###
