"""new

Revision ID: 1048758bd013
Revises: 87a3eea0273e
Create Date: 2025-02-25 09:32:56.220995+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = '1048758bd013'
down_revision: Union[str, None] = '87a3eea0273e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(text("ALTER TABLE users ALTER COLUMN registered_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE environments ALTER COLUMN created_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE environments ALTER COLUMN updated_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE projects ALTER COLUMN created_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE projects ALTER COLUMN updated_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE suites ALTER COLUMN created_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE suites ALTER COLUMN updated_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE cases ALTER COLUMN created_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE cases ALTER COLUMN updated_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE happy_pass ALTER COLUMN created_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE group_run_cases ALTER COLUMN created_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE group_run_cases ALTER COLUMN updated_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE users_demo ALTER COLUMN registered_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE model_results_demo ALTER COLUMN created_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE user_tokens ALTER COLUMN created_at SET DEFAULT now();"))
    op.execute(text("ALTER TABLE billing_transactions ALTER COLUMN created_at SET DEFAULT now();"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("ALTER TABLE users ALTER COLUMN registered_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE environments ALTER COLUMN created_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE environments ALTER COLUMN updated_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE projects ALTER COLUMN created_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE projects ALTER COLUMN updated_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE suites ALTER COLUMN created_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE suites ALTER COLUMN updated_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE cases ALTER COLUMN created_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE cases ALTER COLUMN updated_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE happy_pass ALTER COLUMN created_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE group_run_cases ALTER COLUMN created_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE group_run_cases ALTER COLUMN updated_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE users_demo ALTER COLUMN registered_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE model_results_demo ALTER COLUMN created_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE user_tokens ALTER COLUMN created_at DROP DEFAULT;"))
    op.execute(text("ALTER TABLE billing_transactions ALTER COLUMN created_at DROP DEFAULT;"))
    # ### end Alembic commands ###

