"""group_run_case_id

Revision ID: a4f8fa6c8b36
Revises: c8c63c3e5ab8
Create Date: 2025-06-10 09:26:54.296256+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f8fa6c8b36'
down_revision: Union[str, None] = 'c8c63c3e5ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_cases', sa.Column('group_run_case_id', sa.UUID(), nullable=True))
    op.create_index('idx_run_cases_created_at_group_run_case_id', 'run_cases', ['created_at', 'group_run_case_id'], unique=False)
    op.create_index('idx_run_cases_group_case_created_at_group_run_case_id', 'run_cases', ['group_run_id', 'group_run_case_id', 'created_at'], unique=False)
    op.create_index('idx_run_cases_start_dt_group_run_case_id', 'run_cases', ['start_dt', 'group_run_case_id'], unique=False)
    op.create_index('ix_run_cases_group_run_case_id', 'run_cases', ['group_run_case_id'], unique=False)

    op.execute("""
        UPDATE public.run_cases a
        SET group_run_case_id = b.id
        FROM public.group_run_case_cases b
        WHERE a.case_id = b.case_id
        and a.group_run_id = b.group_run_id
        and a.group_run_id is not null
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_cases_group_run_case_id', table_name='run_cases')
    op.drop_index('idx_run_cases_start_dt_group_run_case_id', table_name='run_cases')
    op.drop_index('idx_run_cases_group_case_created_at_group_run_case_id', table_name='run_cases')
    op.drop_index('idx_run_cases_created_at_group_run_case_id', table_name='run_cases')
    op.drop_column('run_cases', 'group_run_case_id')
    # ### end Alembic commands ###

