"""group_run_id

Revision ID: 1e009daec6dd
Revises: 794516744ee0
Create Date: 2025-02-12 14:25:13.631745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e009daec6dd'
down_revision: Union[str, None] = '794516744ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_cases', sa.Column('group_run_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_cases', 'group_run_id')
    # ### end Alembic commands ###

