"""update variables

Revision ID: eb5f63744ee3
Revises: c75a7774a6ad
Create Date: 2025-07-25 09:19:06.484804+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5f63744ee3'
down_revision: Union[str, None] = 'c75a7774a6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE public.cases
        SET variables = 'Default'
        WHERE variables IS NULL;
    """)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

