"""retries

Revision ID: 6b39840f912a
Revises: 011ab1ef28d8
Create Date: 2025-11-19 11:07:51.709422+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b39840f912a'
down_revision: Union[str, None] = '011ab1ef28d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('retry_enabled', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('environments', sa.Column('retry_timeout', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'retry_timeout')
    op.drop_column('environments', 'retry_enabled')

    # ### end Alembic commands ###

