"""run_case_workspace

Revision ID: 6136e587c35e
Revises: 6cd3273af3c8
Create Date: 2025-03-26 08:25:26.382528+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6136e587c35e'
down_revision: Union[str, None] = '6cd3273af3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_cases', sa.Column('workspace_id', sa.UUID(), nullable=True))

    op.execute("""
    UPDATE run_cases
    SET workspace_id = subquery.workspace_id
    FROM (
        SELECT rc.run_id, p.workspace_id
        FROM run_cases rc
        JOIN cases c ON rc.case_id = c.case_id
        JOIN projects p ON c.project_id = p.project_id
    ) AS subquery
    WHERE run_cases.run_id = subquery.run_id;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_cases', 'workspace_id')
    # ### end Alembic commands ###

