"""'records_project_id'

Revision ID: 00372c3323d3
Revises: 33b856d572a9
Create Date: 2025-10-27 07:52:28.055232+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '00372c3323d3'
down_revision: Union[str, None] = '33b856d572a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('happy_pass', sa.Column('project_id', sa.UUID(), nullable=True))
    conn = op.get_bind()
    # Обновляем project_id для существующих записей
    update_query = text("""
        UPDATE happy_pass hp
        SET project_id = (
            SELECT p.project_id
            FROM projects p
            WHERE p.workspace_id = hp.workspace_id
            AND p.name = 'BB Demo Project'
            LIMIT 1
        )
        WHERE hp.project_id IS NULL
        AND hp.workspace_id IS NOT NULL
        AND EXISTS (
            SELECT 1 FROM projects p
            WHERE p.workspace_id = hp.workspace_id
            AND p.name = 'BB Demo Project'
        );

        UPDATE happy_pass hp
        SET project_id = (
            SELECT p.project_id
            FROM projects p
            WHERE p.workspace_id = hp.workspace_id
            AND p.name = 'SM Demo Project'
            LIMIT 1
        )
        WHERE hp.project_id IS NULL
        AND hp.workspace_id IS NOT NULL
        AND EXISTS (
            SELECT 1 FROM projects p
            WHERE p.workspace_id = hp.workspace_id
            AND p.name = 'SM Demo Project'
        );

        -- Обновляем оставшиеся записи любым проектом из workspace
        UPDATE happy_pass hp
        SET project_id = (
            SELECT p.project_id
            FROM projects p
            WHERE p.workspace_id = hp.workspace_id
            LIMIT 1
        )
        WHERE hp.project_id IS NULL
        AND hp.workspace_id IS NOT NULL
        AND EXISTS (
            SELECT 1 FROM projects p
            WHERE p.workspace_id = hp.workspace_id
        );
    """)
    conn.execute(update_query)

    # Удаляем записи, для которых не нашли проект
    delete_query = text("""
        DELETE FROM happy_pass
        WHERE project_id IS NULL
        AND workspace_id IS NOT NULL;
    """)
    conn.execute(delete_query)

    op.alter_column('happy_pass', 'project_id', nullable=False)

    op.drop_index('ix_happy_pass_user_id_created_at', table_name='happy_pass')
    op.create_index('ix_happy_pass_user_id_created_at', 'happy_pass', ['user_id', 'project_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'happy_pass', 'projects', ['project_id'], ['project_id'])
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'last_check_at'], unique=False)

    op.create_index('ix_happy_pass_workspace_created', 'happy_pass', ['workspace_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_happy_pass_workspace_project', 'happy_pass', ['workspace_id', 'project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'due_date'], unique=False)
    op.drop_constraint(None, 'happy_pass', type_='foreignkey')
    op.drop_index('ix_happy_pass_user_id_created_at', table_name='happy_pass')
    op.create_index('ix_happy_pass_user_id_created_at', 'happy_pass', ['user_id', 'created_at'], unique=False)
    op.drop_index('ix_happy_pass_workspace_project', table_name='happy_pass')
    op.drop_index('ix_happy_pass_workspace_created', table_name='happy_pass')
    # сначала делаем колонку nullable
    op.alter_column('happy_pass', 'project_id', nullable=True)
    op.drop_column('happy_pass', 'project_id')

    # ### end Alembic commands ###
