"""run project_id

Revision ID: fc4137fea8b6
Revises: d71df1be980f
Create Date: 2025-05-22 13:49:01.359557+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4137fea8b6'
down_revision: Union[str, None] = 'd71df1be980f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'last_check_at'], unique=False)
    op.add_column('run_cases', sa.Column('project_id', sa.UUID(), nullable=True))

    op.execute("""
        UPDATE public.run_cases a
        SET project_id = b.project_id
        FROM public.group_run_cases b
        WHERE a.group_run_id = b.group_run_id
        and a.group_run_id is not null
    """)

    op.execute("""
        UPDATE public.run_cases a
        SET project_id = b.project_id
        FROM public.cases b
        WHERE a.case_id = b.case_id
        and a.group_run_id is null
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_cases', 'project_id')
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'due_date'], unique=False)
    # ### end Alembic commands ###

