"""add_default_variables_kit_to_exists_projects

Revision ID: 5eb7a02e21f9
Revises: de1d16f3469a
Create Date: 2025-07-24 07:38:17.604250+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import table, column
from sqlalchemy import select, and_, not_, exists
import uuid
import json
from sqlalchemy import (ARRAY, FLOAT, JSON, Boolean, Column, DateTime,
                        ForeignKey, Index, Integer, Numeric, String, Text,
                        UniqueConstraint, Sequence)


# revision identifiers, used by Alembic.
revision: str = '5eb7a02e21f9'
down_revision: Union[str, None] = 'de1d16f3469a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'last_check_at'], unique=False)


    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # Таблицы для работы
    projects_table = table('projects',
                           column('project_id', UUID),
                           column('workspace_id', UUID),
                           column('user_id', UUID))

    variables_table = table('variables',
                            column('variables_kit_id', UUID),
                            column('variables_kit_name', String),
                            column('variables_kit_description', String),
                            column('project_id', UUID))

    variables_details_table = table('variables_details',
                                    column('variable_details_id', UUID),
                                    column('variables_kit_id', UUID),
                                    column('variable_name', String),
                                    column('variable_value', String))


    # Находим проекты без переменных
    projects_without_variables = session.execute(
        select(projects_table.c.project_id)
        .where(
            not_(
                exists()
                .where(variables_table.c.project_id == projects_table.c.project_id)
            )
        )
    ).fetchall()
    print("projects_without_variables:", len(projects_without_variables))

   # Дефолтные переменные
    default_variables = [
        {"login": "test_user"},
        {"password": "Pa$$w0rd"},
        {"token": None}
    ]

    # Добавляем дефолтные переменные для каждого проекта
    for project in projects_without_variables:
        project_id = project[0]
        
        # Создаем набор переменных
        variables_kit_id = uuid.uuid4()
        session.execute(
            variables_table.insert().values(
                variables_kit_id=variables_kit_id,
                variables_kit_name="Default",
                variables_kit_description="System",
                project_id=project_id
            )
        )

        # Добавляем переменные в набор
        for var in default_variables:
            (name, value), = var.items()
            session.execute(
                variables_details_table.insert().values(
                    variable_details_id=uuid.uuid4(),
                    variables_kit_id=variables_kit_id,
                    variable_name=name,
                    variable_value=json.dumps(value) if value is not None else None
                )
            )

    session.commit()



    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'due_date'], unique=False)

    # Удаляем все дефолтные наборы переменных (те, что имеют variables_kit_name="Default")
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    variables_table = table('variables',
                           column('variables_kit_id', UUID),
                           column('variables_kit_name', String))

    variables_details_table = table('variables_details',
                                   column('variables_kit_id', UUID))

    # Находим ID всех дефолтных наборов
    default_kits = session.execute(
        select(variables_table.c.variables_kit_id)
        .where(variables_table.c.variables_kit_name == "Default")
    ).fetchall()

    # Удаляем сначала детали, затем наборы
    for kit in default_kits:
        kit_id = kit[0]
        session.execute(
            variables_details_table.delete()
            .where(variables_details_table.c.variables_kit_id == kit_id)
        )
        session.execute(
            variables_table.delete()
            .where(variables_table.c.variables_kit_id == kit_id)
        )

    session.commit()
    # ### end Alembic commands ###

