"""project_id in case

Revision ID: 203d21e9a72b
Revises: 2fc00df71548
Create Date: 2025-02-24 11:05:27.238310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203d21e9a72b'
down_revision: Union[str, None] = '2fc00df71548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('project_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'project_id')
    # ### end Alembic commands ###

