"""user_flags

Revision ID: 722ed25b45ed
Revises: c8a830821ab9
Create Date: 2025-08-05 09:28:58.515183+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '722ed25b45ed'
down_revision: Union[str, None] = 'c8a830821ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flag_catalog',
    sa.Column('flag_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('default_shown', sa.Boolean(), nullable=True),
    sa.Column('default_view_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('flag_name')
    )
    op.create_table('user_flags',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )

    conn = op.get_bind()
    
    # Заполняем справочник флагов
    flags_to_insert = [
        {
            'flag_name': 'welcome',
            'description': 'Приветственное сообщение при первом входе',
            'default_shown': False,
            'default_view_count': 0,
            'is_active': True
        },
        {
            'flag_name': 'onboarding',
            'description': 'Прохождение онбординга',
            'default_shown': False,
            'default_view_count': 0,
            'is_active': True
        },
        {
            'flag_name': 'chat_bot',
            'description': 'Показ чат-бота',
            'default_shown': False,
            'default_view_count': 0,
            'is_active': True
        }
    ]
    
    for flag in flags_to_insert:
        conn.execute(text("""
            INSERT INTO flag_catalog (flag_name, description, default_shown, default_view_count, is_active)
            VALUES (:flag_name, :description, :default_shown, :default_view_count, :is_active)
        """), flag)
    
    # Заполняем флаги для существующих пользователей
    conn.execute(text("""
        INSERT INTO user_flags (user_id, flags)
        SELECT 
            user_id, 
            jsonb_object_agg(
                flag_name, 
                jsonb_build_object(
                    'shown', default_shown,
                    'view_count', default_view_count,
                    'last_update', now()::text
                )
            ) as flags
        FROM 
            users,
            flag_catalog
        GROUP BY user_id
        ON CONFLICT (user_id) DO NOTHING
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_flags')
    op.drop_table('flag_catalog')
    # ### end Alembic commands ###

