"""new

Revision ID: 2b957620912e
Revises: 
Create Date: 2025-02-03 14:39:33.631532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b957620912e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('permission', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role')
    )
    op.execute("""
    insert into roles (role, description) values ('ROLE_USER', 'обычный пользователь после регистрации');
    insert into roles (role, description) values ('ROLE_USER_PREMIUM', 'пользователь с полным доступом');
    insert into roles (role, description) values ('ROLE_ADMIN', 'админ');
    insert into roles (role, description) values ('ROLE_ADMIN_EXT', 'просмотр всех ранов');
    """)

    op.create_table('templates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('template_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users_demo',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('billing_transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_billing_transactions_created_at', 'billing_transactions', ['created_at'], unique=False)
    op.create_index('ix_billing_transactions_user_id', 'billing_transactions', ['user_id'], unique=False)
    op.create_index('ix_billing_transactions_user_id_created_at', 'billing_transactions', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_billing_transactions_user_id_created_at_amount', 'billing_transactions', ['user_id', 'created_at', 'amount'], unique=False)
    op.create_table('happy_pass',
    sa.Column('happy_pass_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.JSON()), nullable=False),
    sa.Column('full_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('action_plan', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('happy_pass_id')
    )
    op.create_index('ix_happy_pass_created_at', 'happy_pass', ['created_at'], unique=False)
    op.create_index('ix_happy_pass_user_id', 'happy_pass', ['user_id'], unique=False)
    op.create_index('ix_happy_pass_user_id_created_at', 'happy_pass', ['user_id', 'created_at'], unique=False)
    op.create_table('model_results_demo',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_demo.user_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('projects',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_index('ix_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_table('user_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    op.create_table('users_to_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_users_to_roles_user_id'), 'users_to_roles', ['user_id'], unique=False)
    op.create_table('suites',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suite_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['suites.suite_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('suite_id')
    )
    op.create_index('ix_suites_name', 'suites', ['name'], unique=False)
    op.create_index('ix_suites_parent_id', 'suites', ['parent_id'], unique=False)
    op.create_index('ix_suites_project', 'suites', ['project_id'], unique=False)
    op.create_table('cases',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('suite_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('before_steps', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('after_steps', sa.JSON(), nullable=False),
    sa.Column('validation_steps', sa.JSON(), nullable=False),
    sa.Column('validation_task', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('llm_response', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_reason', sa.JSON(), nullable=False),
    sa.Column('action_plan', sa.JSON(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['suites.suite_id'], ),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_cases_case_id_suite_id', 'cases', ['case_id', 'suite_id'], unique=False)
    op.create_index('ix_cases_name', 'cases', ['name'], unique=False)
    op.create_index('ix_cases_suite_id', 'cases', ['suite_id'], unique=False)
    op.create_table('run_cases',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('run_summary', sa.String(), nullable=True),
    sa.Column('video', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('start_dt', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_dt', sa.TIMESTAMP(), nullable=True),
    sa.Column('complete_time', sa.FLOAT(), nullable=True),
    sa.Column('current_case_version', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_run_cases_created_at_case_id', 'run_cases', ['created_at', 'case_id'], unique=False)
    op.create_index('idx_run_cases_created_at_run_id', 'run_cases', ['created_at', 'run_id'], unique=False)
    op.create_index('idx_run_cases_start_dt_case_id', 'run_cases', ['start_dt', 'case_id'], unique=False)
    op.create_index('idx_run_cases_start_dt_run_id', 'run_cases', ['start_dt', 'run_id'], unique=False)
    op.create_index('ix_run_cases_case_id', 'run_cases', ['case_id'], unique=False)
    op.create_index('ix_run_cases_created_at', 'run_cases', ['created_at'], unique=False)
    op.create_index('ix_run_cases_end_dt', 'run_cases', ['end_dt'], unique=False)
    op.create_index('ix_run_cases_start_dt', 'run_cases', ['start_dt'], unique=False)
    op.create_index('ix_run_cases_status', 'run_cases', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_cases_status', table_name='run_cases')
    op.drop_index('ix_run_cases_start_dt', table_name='run_cases')
    op.drop_index('ix_run_cases_end_dt', table_name='run_cases')
    op.drop_index('ix_run_cases_created_at', table_name='run_cases')
    op.drop_index('ix_run_cases_case_id', table_name='run_cases')
    op.drop_index('idx_run_cases_start_dt_run_id', table_name='run_cases')
    op.drop_index('idx_run_cases_start_dt_case_id', table_name='run_cases')
    op.drop_index('idx_run_cases_created_at_run_id', table_name='run_cases')
    op.drop_index('idx_run_cases_created_at_case_id', table_name='run_cases')
    op.drop_table('run_cases')
    op.drop_index('ix_cases_suite_id', table_name='cases')
    op.drop_index('ix_cases_name', table_name='cases')
    op.drop_index('idx_cases_case_id_suite_id', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_suites_project', table_name='suites')
    op.drop_index('ix_suites_parent_id', table_name='suites')
    op.drop_index('ix_suites_name', table_name='suites')
    op.drop_table('suites')
    op.drop_index(op.f('ix_users_to_roles_user_id'), table_name='users_to_roles')
    op.drop_table('users_to_roles')
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_index('ix_projects_user_id', table_name='projects')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_table('projects')
    op.drop_table('model_results_demo')
    op.drop_index('ix_happy_pass_user_id_created_at', table_name='happy_pass')
    op.drop_index('ix_happy_pass_user_id', table_name='happy_pass')
    op.drop_index('ix_happy_pass_created_at', table_name='happy_pass')
    op.drop_table('happy_pass')
    op.drop_index('ix_billing_transactions_user_id_created_at_amount', table_name='billing_transactions')
    op.drop_index('ix_billing_transactions_user_id_created_at', table_name='billing_transactions')
    op.drop_index('ix_billing_transactions_user_id', table_name='billing_transactions')
    op.drop_index('ix_billing_transactions_created_at', table_name='billing_transactions')
    op.drop_table('billing_transactions')
    op.drop_table('users_demo')
    op.drop_table('users')
    op.drop_table('templates')
    op.drop_table('roles')
    # ### end Alembic commands ###

