"""job

Revision ID: 219971100f98
Revises: 710a414872bc
Create Date: 2025-03-20 11:40:03.482740+00:00

"""
from typing import Sequence, Union
from sqlalchemy.sql import text
from uuid import uuid4
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '219971100f98'
down_revision: Union[str, None] = '710a414872bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_limits',
    sa.Column('limit_id', sa.UUID(), nullable=False),
    sa.Column('tariff_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.tariff_id'], ),
    sa.PrimaryKeyConstraint('limit_id')
    )
    op.create_index('idx_tariff_limits_tariff_id', 'tariff_limits', ['tariff_id'], unique=False)
    op.create_table('workspace_usage',
    sa.Column('usage_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_reset', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index('idx_workspace_usage_workspace_id', 'workspace_usage', ['workspace_id'], unique=False)
    op.drop_column('tariffs', 'limits')


    # Insert initial data into the tariff_limits table
    conn = op.get_bind()

    # Define the limitations for each tariff
    limits = {
        'starter': {
            'start_group_run': 400,
            'save_happy_pass': 10,
            'invite_user_workspace': 0,
            'max_concurrent_tasks': 1,
        },
        'individual': {
            'start_group_run': 1000,
            'save_happy_pass': 100,
            'invite_user_workspace': 2,
            'max_concurrent_tasks': 1,
        },
        'corporate': {
            'start_group_run': -1,
            'save_happy_pass': -1,
            'invite_user_workspace': -1,
            'max_concurrent_tasks': 3,
        }
    }

    # Insert data
    for tariff_name, features in limits.items():
        tariff_id_result = conn.execute(text(f"SELECT tariff_id FROM tariffs WHERE tariff_name = :tariff_name"),{"tariff_name":tariff_name}).fetchone()
        if tariff_id_result:
            tariff_id = tariff_id_result[0]
            for feature_name, limit_value in features.items():
                conn.execute(
                    text("INSERT INTO tariff_limits (limit_id, tariff_id, feature_name, limit_value) VALUES (:limit_id, :tariff_id, :feature_name, :limit_value)"),
                    {"limit_id": str(uuid4()), "tariff_id": tariff_id, "feature_name": feature_name, "limit_value": limit_value}
                )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('limits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('idx_workspace_usage_workspace_id', table_name='workspace_usage')
    op.drop_table('workspace_usage')
    op.drop_index('idx_tariff_limits_tariff_id', table_name='tariff_limits')
    op.drop_table('tariff_limits')
    # ### end Alembic commands ###

