"""env

Revision ID: 794516744ee0
Revises: f57fec0fcfd4
Create Date: 2025-02-11 12:21:53.268001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794516744ee0'
down_revision: Union[str, None] = 'f57fec0fcfd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('browser', sa.String(), nullable=False),
    sa.Column('operation_system', sa.String(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('environment_id')
    )
    op.create_index('ix_project', 'environments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project', table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###

