"""payment_history

Revision ID: b6318d088f29
Revises: 69a6fff65034
Create Date: 2025-04-29 14:59:16.835618+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6318d088f29'
down_revision: Union[str, None] = '69a6fff65034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
        CREATE SEQUENCE invoice_seq
        START WITH 1
        INCREMENT BY 1
        MINVALUE 1
        MAXVALUE 999999999999999
        NO CYCLE
        CACHE 1
    """)

    op.create_table('payment_history',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=15), server_default=sa.text("nextval('invoice_seq')"), nullable=False),
    sa.Column('x_requests_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('services', sa.String(), nullable=False),
    sa.Column('tariff_id', sa.UUID(), nullable=False),
    sa.Column('stream_count', sa.Integer(), nullable=True),
    sa.Column('cnt_months', sa.Integer(), nullable=False),
    sa.Column('stream_only', sa.Boolean(), nullable=True),
    sa.Column('cur', sa.String(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(scale=2), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('payment_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('ix_payment_history_created_at', 'payment_history', ['created_at'], unique=False)
    op.create_index('ix_payment_history_status', 'payment_history', ['status'], unique=False)
    op.create_index('ix_payment_history_workspace_id', 'payment_history', ['workspace_id'], unique=False)
    op.create_index('ix_payment_history_workspace_id_status', 'payment_history', ['workspace_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_id_status', table_name='payment_history')
    op.drop_index('ix_payment_history_workspace_id', table_name='payment_history')
    op.drop_index('ix_payment_history_status', table_name='payment_history')
    op.drop_index('ix_payment_history_created_at', table_name='payment_history')
    op.drop_table('payment_history')
    # ### end Alembic commands ###

