"""variable_config

Revision ID: 29bf1d6e0d5d
Revises: 6b39840f912a
Create Date: 2025-11-25 08:40:51.078303+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29bf1d6e0d5d'
down_revision: Union[str, None] = '6b39840f912a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DROP TABLE IF EXISTS run_cases_backup;
        DROP TABLE IF EXISTS cases_backup;
        DROP TABLE IF EXISTS case_shared_steps_backup;
    """)

    op.add_column('variables_details', sa.Column('variable_config', sa.JSON(), nullable=True))
    op.add_column('variables_details', sa.Column('variable_description', sa.String(), nullable=True))

    # Заполняем variable_config на основе variable_value
    op.execute("""
        UPDATE variables_details
        SET variable_config = jsonb_build_object(
            'type', 'simple',
            'value', variable_value
        )
    """)

    # Теперь делаем variable_config NOT NULL
    op.alter_column('variables_details', 'variable_config', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variables_details', 'variable_description')
    op.drop_column('variables_details', 'variable_config')
    op.create_table('case_shared_steps_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('shared_steps_id', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('cases_backup',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('suite_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('before_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('after_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('validation_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('validation_task', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('llm_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('validation_reason', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action_plan', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action_plan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('before_browser_start', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('variables', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shared_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.create_table('run_cases_backup',
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('run_summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('start_dt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_dt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('complete_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_case_version', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cnt_run', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('extra', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('group_run_case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('background_video_generate', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###

