"""new

Revision ID: a94b62cc4598
Revises: c988b932f09a
Create Date: 2025-02-13 15:44:47.623066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94b62cc4598'
down_revision: Union[str, None] = 'c988b932f09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_run_case_cases', sa.Column('suite_hierarchy', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_run_case_cases', 'suite_hierarchy')
    # ### end Alembic commands ###

