"""start_kit

Revision ID: 816c859f439d
Revises: fc4137fea8b6
Create Date: 2025-05-28 07:28:53.782851+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816c859f439d'
down_revision: Union[str, None] = 'fc4137fea8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('source', sa.String(), nullable=True))
    op.add_column('users', sa.Column('host', sa.String(), nullable=True))

    op.execute("""
        UPDATE public.users a
        SET source = 'signup'
        WHERE email not like '%.mock%'
    """)

    op.execute("""
        UPDATE public.users a
        SET source = 'jira'
        WHERE email like '%.mock%'
    """)

    op.execute("""
        UPDATE public.users a
        SET host = 'api.example.com'
        WHERE host is null
    """)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'host')
    op.drop_column('users', 'source')
    # ### end Alembic commands ###

