"""plans

Revision ID: 7ffb85f0d786
Revises: 2a5ddb44e981
Create Date: 2025-04-24 12:03:04.679217+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffb85f0d786'
down_revision: Union[str, None] = '2a5ddb44e981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff_limits', sa.Column('feature_full_name', sa.String(), nullable=True))
    op.add_column('tariffs', sa.Column('tariff_full_name', sa.String(), nullable=True))
    op.add_column('tariffs', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tariffs', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('tariffs', sa.Column('cur', sa.String(), nullable=True))
    op.add_column('tariffs', sa.Column('period', sa.String(), nullable=True))
    op.add_column('tariffs', sa.Column('buy_tariff_manual_only', sa.Boolean(), nullable=True))
    op.add_column('tariffs', sa.Column('best_value', sa.Boolean(), nullable=True))
    op.add_column('tariffs', sa.Column('can_buy_streams', sa.Boolean(), nullable=True))
    op.add_column('tariffs', sa.Column('visible', sa.Boolean(), nullable=True))

    op.drop_column('users', 'max_concurrent_tasks')
    op.add_column('workspaces', sa.Column('max_concurrent_tasks', sa.Integer(), nullable=True))

    op.execute("""
        UPDATE public.tariff_limits
        SET feature_full_name = CASE
            WHEN limit_value = 0 THEN '1 test cases'
            WHEN limit_value = -1 THEN 'unlimited test cases'
            ELSE limit_value::text || ' test cases'
        END
        WHERE feature_name = 'start_group_run'
    """)

    op.execute("""
        UPDATE public.tariff_limits
        SET feature_full_name = CASE
            WHEN limit_value = 0 THEN '1 users'
            WHEN limit_value = -1 THEN 'unlimited users'
            ELSE limit_value::text || ' users'
        END
        WHERE feature_name = 'invite_user_workspace'
    """)

    op.execute("""
        UPDATE public.tariff_limits
        SET feature_full_name = CASE
            WHEN limit_value = 0 THEN '1 stream'
            WHEN limit_value = -1 THEN 'unlimited stream'
            ELSE limit_value::text || ' stream'
        END
        WHERE feature_name = 'max_concurrent_tasks'
    """)

    op.execute("""
        UPDATE public.tariff_limits
        SET feature_full_name = CASE
            WHEN limit_value = 0 THEN '1 recorder entries'
            WHEN limit_value = -1 THEN 'unlimited recorder entries'
            ELSE limit_value::text || ' recorder entries'
        END
        WHERE feature_name = 'save_happy_pass'
    """)

    # тарифы
    op.execute("""
        UPDATE public.tariffs
        SET tariff_full_name = 'Free',
            description = 'Suitable for familiarization with all functions',
            discount = '0',
            cur = 'руб.',
            period = 'month',
            buy_tariff_manual_only = '0',
            best_value = '0',
            can_buy_streams = '0',
            visible = '1'

        WHERE tariff_name = 'starter'
    """)

    op.execute("""
        UPDATE public.tariffs
        SET tariff_full_name = 'Starter',
            description = 'Covers all needs for product testing for up to 3 users',
            discount = '20',
            cur = 'руб.',
            period = 'month',
            buy_tariff_manual_only = '0',
            best_value = '0',
            can_buy_streams = '0',
            visible = '1'

        WHERE tariff_name = 'individual'
    """)

    op.execute("""

        INSERT INTO public.tariffs
        (tariff_id, tariff_name, tariff_full_name, description, discount, cur, period, buy_tariff_manual_only, best_value, can_buy_streams, cnt_months, price, visible)
        VALUES(gen_random_uuid(), 'team', 'Team', 'Unlimited access to all resources to automate your testing', '20', 'руб.', 'month', '0', '1', '1', '1', '30000', '1');

    """)

    op.execute("""
        UPDATE public.tariffs
        SET tariff_full_name = 'Enterprise - OnPrem',
            description = 'Unlimited access to all resources to automate your testing',
            discount = '20',
            cur = 'руб.',
            period = 'month',
            buy_tariff_manual_only = '1',
            best_value = '0',
            can_buy_streams = '1',
            visible = '1'

        WHERE tariff_name = 'corporate'
    """)

    op.execute("""
        UPDATE public.tariffs
        SET tariff_full_name = 'Нестандарт',
            description = 'кастомный тариф',
            discount = '20',
            cur = 'руб.',
            period = 'month',
            buy_tariff_manual_only = '1',
            best_value = '0',
            can_buy_streams = '1',
            visible = '0'

        WHERE tariff_name not in ('starter', 'individual', 'corporate', 'team')
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'max_concurrent_tasks')
    op.add_column('users', sa.Column('max_concurrent_tasks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tariffs', 'best_value')
    op.drop_column('tariffs', 'buy_tariff_manual_only')
    op.drop_column('tariffs', 'period')
    op.drop_column('tariffs', 'cur')
    op.drop_column('tariffs', 'discount')
    op.drop_column('tariffs', 'description')
    op.drop_column('tariffs', 'tariff_full_name')
    op.drop_column('tariff_limits', 'feature_full_name')
    # ### end Alembic commands ###
