"""group runs

Revision ID: c988b932f09a
Revises: 9da72a8751d4
Create Date: 2025-02-13 13:59:25.227526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c988b932f09a'
down_revision: Union[str, None] = '9da72a8751d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_run_cases',
    sa.Column('group_run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('environment', sa.UUID(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parallel_exec', sa.Boolean(), nullable=True),
    sa.Column('host', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_run_id')
    )
    op.create_table('group_run_case_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_run_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('suite_id', sa.UUID(), nullable=False),
    sa.Column('suite_name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('current_case_version', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['group_run_id'], ['group_run_cases.group_run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_run_case_cases')
    op.drop_table('group_run_cases')
    # ### end Alembic commands ###

