"""run

Revision ID: b8f989e5b594
Revises: 2b957620912e
Create Date: 2025-02-07 10:37:21.663832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8f989e5b594'
down_revision: Union[str, None] = '2b957620912e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_cases', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('run_cases', sa.Column('cnt_run', sa.Integer(), nullable=True))
    op.alter_column('run_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index('ix_run_cases_cnt_run', 'run_cases', ['cnt_run'], unique=False)
    op.create_index('ix_run_cases_user_id', 'run_cases', ['user_id'], unique=False)
    op.drop_constraint('run_cases_case_id_fkey', 'run_cases', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('run_cases_case_id_fkey', 'run_cases', 'cases', ['case_id'], ['case_id'])
    op.drop_index('ix_run_cases_user_id', table_name='run_cases')
    op.drop_index('ix_run_cases_cnt_run', table_name='run_cases')
    op.alter_column('run_cases', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('run_cases', 'cnt_run')
    op.drop_column('run_cases', 'user_id')
    # ### end Alembic commands ###

