"""workspace_status

Revision ID: db7e320355f7
Revises: 219971100f98
Create Date: 2025-03-20 15:09:27.543214+00:00

"""
from typing import Sequence, Union
from sqlalchemy.sql import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7e320355f7'
down_revision: Union[str, None] = '219971100f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('status', sa.String(), nullable=False, server_default='Active'))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'status')
    # ### end Alembic commands ###
