"""tariff_start_date

Revision ID: 710a414872bc
Revises: 0e305fa1b476
Create Date: 2025-03-19 14:25:06.830025+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710a414872bc'
down_revision: Union[str, None] = '0e305fa1b476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('tariff_start_date', sa.DateTime(timezone=True), nullable=True))

    op.execute("""
        UPDATE public.workspaces
        SET tariff_start_date = created_at
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'tariff_start_date')
    # ### end Alembic commands ###
