"""test

Revision ID: 87a3eea0273e
Revises: eb82c16360e6
Create Date: 2025-02-25 09:20:23.279525+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = '87a3eea0273e'
down_revision: Union[str, None] = 'eb82c16360e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        text("ALTER TABLE run_cases ALTER COLUMN created_at SET DEFAULT now();")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        text("ALTER TABLE run_cases ALTER COLUMN created_at DROP DEFAULT;")
    )
    # ### end Alembic commands ###

