"""new_permissions

Revision ID: 9b92a4bc2fe4
Revises: 7ffb85f0d786
Create Date: 2025-04-24 13:21:42.542306+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b92a4bc2fe4'
down_revision: Union[str, None] = '7ffb85f0d786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE public.roles
        SET role='admin', permission='{"endpoints": ["get_workspace_memberships_list", "get_case_by_external_id", "generate_case_from_record", "get_case_by_case_id",
        "get_project_by_id", "list_projects", "list_suites", "create_new_project", "create_new_suite", "create_new_case", "copy_case_by_case_id",
        "update_existing_project","update_existing_suite","change_suite_position",
        "update_existing_case","change_case_position","delete_existing_project","delete_existing_suite","delete_existing_case", "get_user_tree_route",
        "get_list_environments", "get_environments_by_id", "create_environment","update_environment","delete_environments",
        "happy_passes_list","happy_passes_full","happypass_autosop_generate","happypass_action_plan_update","delete_existing_happy_pass", "get_runs_tree_route",
        "get_run_by_id", "start_run_by_case_id", "stop_run_by_id", "create_group_run_by_cases", "update_group_run_case_untested", "delete_group_run_case_by_id",
        "group_run_case_tree", "start_run_by_group_run_id", "stop_run_by_group_run_id", "complete_run_cases_by_run_id","step_passed_run_case_by_run_id",
        "delete_cases_in_group_run", "invite_user", "edit_user_workspace_membership", "remove_user_workspace_membership",
        "get_free_streams_for_grouprun_by_project_id", "get_free_streams_for_active_workspace", "get_list_tariffs_limits_plan"]}'::json,
        description='Administrator'
        WHERE role='admin';
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
