"""idx

Revision ID: 121bfb1581f3
Revises: 3d14a79200be
Create Date: 2025-03-05 07:28:41.117773+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121bfb1581f3'
down_revision: Union[str, None] = '3d14a79200be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_project_id_workspace_id', 'projects', ['project_id', 'workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_id_workspace_id', table_name='projects')
    # ### end Alembic commands ###

