"""background_video_generate

Revision ID: fe1aab16e453
Revises: a4f8fa6c8b36
Create Date: 2025-07-08 12:19:13.847709+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1aab16e453'
down_revision: Union[str, None] = 'a4f8fa6c8b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_run_cases', sa.Column('background_video_generate', sa.Boolean(), nullable=True))
    op.add_column('run_cases', sa.Column('background_video_generate', sa.Boolean(), nullable=True))
    op.add_column('cases', sa.Column('before_browser_start', sa.JSON(), nullable=True))
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'last_check_at'], unique=False)
    # ### end Alembic commands ###

    op.execute("""
        UPDATE public.group_run_cases
        SET background_video_generate = true
        WHERE background_video_generate is null
    """)

    op.execute("""
        UPDATE public.run_cases
        SET background_video_generate = true
        WHERE background_video_generate is null
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'due_date'], unique=False)
    op.drop_column('group_run_cases', 'background_video_generate')
    op.drop_column('run_cases', 'background_video_generate')
    op.drop_column('cases', 'before_browser_start')
    # ### end Alembic commands ###

