"""logs add fields

Revision ID: ca82340b0b4d
Revises: 0725be874f76
Create Date: 2025-04-14 11:29:29.169518+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca82340b0b4d'
down_revision: Union[str, None] = '0725be874f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entries', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('log_entries', sa.Column('user_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_entries', 'user_username')
    op.drop_column('log_entries', 'user_email')
    # ### end Alembic commands ###

