"""workspaces

Revision ID: 81c050f07d10
Revises: 1048758bd013
Create Date: 2025-02-28 10:33:47.933344+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import table, column
from sqlalchemy import Integer, String, DateTime, func, Numeric
import datetime
import uuid


# revision identifiers, used by Alembic.
revision: str = '81c050f07d10'
down_revision: Union[str, None] = '1048758bd013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



bind = op.get_bind()
session = sa.orm.Session(bind=bind)

tariffs_table = table('tariffs',
                      column('tariff_id', UUID),
                      column('tariff_name', String),
                      column('limits', sa.JSON),
                      column('cnt_months', Integer),
                      column('price', Numeric))

roles_table = table('roles',
                    column('role_id', Integer),
                    column('role', String),
                    column('permission', sa.JSON),
                    column('description', String))

workspaces_table = table('workspaces',
                         column('workspace_id', UUID),
                         column('name', String),
                         column('owner_id', UUID),
                         column('tariff_id', UUID),
                         column('tariff_expiration', DateTime),
                         column('created_at', DateTime),
                         column('updated_at', DateTime))

workspace_memberships_table = table('workspace_memberships',
                                    column('id', UUID),
                                    column('workspace_id', UUID),
                                    column('user_id', UUID),
                                    column('role', String),
                                    column('role_title', String),
                                    column('status', String),
                                    column('email', String),
                                    column('last_action_date', DateTime))

project_users_table = table('project_users',
                            column('id', UUID),
                            column('project_id', UUID),
                            column('workspace_id', UUID),
                            column('user_id', UUID),
                            column('role', String))

projects_table = table('projects',
                       column('project_id', UUID),
                       column('workspace_id', UUID),
                       column('user_id', UUID))

users_table = table('users',
                    column('user_id', UUID),
                    column('email', String),
                    column('active_workspace_id', UUID),
                    column('registered_at', DateTime))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('tariff_id', sa.UUID(), nullable=False),
    sa.Column('tariff_name', sa.String(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=True),
    sa.Column('cnt_months', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(scale=2), nullable=False),
    sa.PrimaryKeyConstraint('tariff_id')
    )
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('tariff_id', sa.UUID(), nullable=True),
    sa.Column('tariff_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.tariff_id'], ),
    sa.PrimaryKeyConstraint('workspace_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workspace_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_action_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.role'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['role'], ['roles.role'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_to_roles')
    op.add_column('projects', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'workspaces', ['workspace_id'], ['workspace_id'])
    op.add_column('users', sa.Column('active_workspace_id', sa.UUID(), nullable=True))

    tariffs = [
        {'tariff_id': uuid.uuid4(), 'tariff_name': 'starter', 'limits': {}, 'cnt_months': 2, 'price': 0},
        {'tariff_id': uuid.uuid4(), 'tariff_name': 'individual', 'limits': {}, 'cnt_months': 1, 'price': 10000},
        {'tariff_id': uuid.uuid4(), 'tariff_name': 'corporate', 'limits': {}, 'cnt_months': 1, 'price': 50000}
    ]

    for tariff in tariffs:
        session.execute(
            tariffs_table.insert().values(**tariff)
        )
    session.commit()

    new_roles = [{'role': 'admin', 'permission': {}, 'description': 'Administrator'},
                 {'role': 'member', 'permission': {}, 'description': 'Member'},
                 {'role': 'read-only', 'permission': {}, 'description': 'Read-Only'},
                 {'role': 'system', 'permission': {}, 'description': 'System User'}]

    for role in new_roles:
        session.execute(
            roles_table.insert().values(**role)
        )
    session.commit()

    # Fetch users
    users = session.execute(sa.select(
        users_table.c.user_id,
        users_table.c.email,
        users_table.c.registered_at
    )).fetchall()

    # Fetch starter tariff
    starter_tariff = session.execute(sa.select(tariffs_table.c.tariff_id).where(tariffs_table.c.tariff_name == 'starter')).scalar()

    # Insert workspaces and memberships
    for user in users:
        workspace_id = uuid.uuid4()

        # Insert Workspace
        session.execute(workspaces_table.insert().values(
            workspace_id=workspace_id,
            name=user.email,
            owner_id=user.user_id,
            tariff_id=starter_tariff,
            tariff_expiration=user.registered_at + datetime.timedelta(days=60),
            created_at=func.now(),
            updated_at=func.now()
        ))

        # Update user with active_workspace_id
        session.execute(users_table.update().where(users_table.c.user_id == user.user_id).values(
            active_workspace_id=workspace_id
        ))

        # Insert WorkspaceMembership
        session.execute(workspace_memberships_table.insert().values(
            id=uuid.uuid4(),
            workspace_id=workspace_id,
            user_id=user.user_id,
            role='admin',
            role_title='QA Manager',
            status='Active',
            email=user.email,
            last_action_date=func.now()
        ))

        projects = session.execute(sa.select(projects_table.c.project_id).where(projects_table.c.user_id == user.user_id)).fetchall()

        for project in projects:
            # Update project with workspace_id
            session.execute(projects_table.update().where(projects_table.c.project_id == project[0]).values(
                workspace_id=workspace_id
            ))

            # Insert ProjectUser record
            session.execute(project_users_table.insert().values(
                id=uuid.uuid4(),
                project_id=project[0],
                workspace_id=workspace_id,
                user_id=user.user_id,
                role='admin'
            ))

    op.alter_column('users', 'active_workspace_id', existing_type=sa.UUID(), nullable=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_workspace_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'workspace_id')
    op.create_table('users_to_roles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='users_to_roles_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='users_to_roles_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='users_to_roles_pkey')
    )
    op.create_index('ix_users_to_roles_user_id', 'users_to_roles', ['user_id'], unique=False)
    op.drop_table('project_users')
    op.drop_table('workspace_memberships')
    op.drop_table('workspaces')
    op.drop_table('tariffs')


    # ### end Alembic commands ###

