"""idx

Revision ID: 06200dc8e825
Revises: 69d239f113fb
Create Date: 2025-03-06 15:04:37.560446+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06200dc8e825'
down_revision: Union[str, None] = '69d239f113fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_project_users_project_id_workspace_user', 'project_users', ['project_id', 'workspace_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_users_project_id_workspace_user', table_name='project_users')
    # ### end Alembic commands ###

