"""idx

Revision ID: ccc533610ebd
Revises: 491703660c22
Create Date: 2025-03-28 07:49:54.204511+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc533610ebd'
down_revision: Union[str, None] = '491703660c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_group_run_cases_group_run_id', 'group_run_cases', ['group_run_id'], unique=False)
    op.create_index('idx_group_run_created_at', 'group_run_cases', ['created_at'], unique=False)
    op.create_index('idx_group_run_status', 'group_run_cases', ['status'], unique=False)
    op.create_index('ix_group_run_cases_project_id', 'group_run_cases', ['project_id'], unique=False)
    op.create_index('idx_run_cases_status_created_at', 'run_cases', ['status', 'created_at'], unique=False)
    # op.create_index('ix_run_cases_case_type', 'run_cases', [sa.text("(current_case_version->>'case_type_in_run')")], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_run_cases_case_type', table_name='run_cases')
    op.drop_index('idx_run_cases_status_created_at', table_name='run_cases')
    op.drop_index('ix_group_run_cases_project_id', table_name='group_run_cases')
    op.drop_index('idx_group_run_status', table_name='group_run_cases')
    op.drop_index('idx_group_run_created_at', table_name='group_run_cases')
    op.drop_index('idx_group_run_cases_group_run_id', table_name='group_run_cases')
    # ### end Alembic commands ###

