"""variables

Revision ID: a8cc5bcbe29c
Revises: 89e793fce384
Create Date: 2025-07-23 10:56:46.578659+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cc5bcbe29c'
down_revision: Union[str, None] = '89e793fce384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variables',
    sa.Column('variables_kit_id', sa.UUID(), nullable=False),
    sa.Column('variables_kit_name', sa.String(), nullable=False),
    sa.Column('variables_kit_description', sa.String(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('variables_kit_id')
    )
    op.create_index('ix_variables_project', 'variables', ['project_id'], unique=False)
    op.create_table('variables_details',
    sa.Column('variable_details_id', sa.UUID(), nullable=False),
    sa.Column('variables_kit_id', sa.UUID(), nullable=False),
    sa.Column('variable_name', sa.String(), nullable=False),
    sa.Column('variable_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['variables_kit_id'], ['variables.variables_kit_id'], ),
    sa.PrimaryKeyConstraint('variable_details_id')
    )
    op.create_index('idx_variables_details_tariff_id', 'variables_details', ['variables_kit_id'], unique=False)
    op.create_index('idx_variables_details_tariff_id_feature_name', 'variables_details', ['variables_kit_id', 'variable_name'], unique=False)
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'due_date'], unique=False)

    op.execute("""
        UPDATE public.roles
        SET role='admin', permission='{"endpoints": ["get_workspace_memberships_list", "get_case_by_external_id", "generate_case_from_record", "get_case_by_case_id",
        "get_project_by_id", "list_projects", "list_suites", "create_new_project", "create_new_suite", "create_new_case", "copy_case_by_case_id",
        "update_existing_project","update_existing_suite","change_suite_position",
        "update_existing_case","change_case_position","delete_existing_project","delete_existing_suite","delete_existing_case", "get_user_tree_route",
        "get_list_environments", "get_environments_by_id", "create_environment","update_environment","delete_environments",
        "happy_passes_list","happy_passes_full","happypass_autosop_generate","happypass_action_plan_update","delete_existing_happy_pass", "get_runs_tree_route",
        "get_run_by_id", "start_run_by_case_id", "stop_run_by_id", "create_group_run_by_cases", "update_group_run_case_untested", "delete_group_run_case_by_id",
        "group_run_case_tree", "start_run_by_group_run_id", "stop_run_by_group_run_id", "complete_run_cases_by_run_id","step_passed_run_case_by_run_id",
        "delete_cases_in_group_run", "invite_user", "edit_user_workspace_membership", "remove_user_workspace_membership",
        "get_free_streams_for_grouprun_by_project_id", "get_free_streams_for_active_workspace", "get_list_tariffs_limits_plan",
        "get_current_tariffs_limits_usage", "get_calculate_tariff_price",
        "get_calculate_additional_stream", "create_corporate_invoice",
        "get_user_transactions_billing", "create_individual_payment", "update_start_kit_to_workspace", "copy_group_runs_by_ids",
        "get_list_variables_kit", "get_variables_kit_by_id", "create_new_variables_kit", "update_variables_kit", "delete_variable_kit" ]}'::json,
        description='Administrator'
        WHERE role='admin';
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'last_check_at'], unique=False)
    op.drop_index('idx_variables_details_tariff_id_feature_name', table_name='variables_details')
    op.drop_index('idx_variables_details_tariff_id', table_name='variables_details')
    op.drop_table('variables_details')
    op.drop_index('ix_variables_project', table_name='variables')
    op.drop_table('variables')
    # ### end Alembic commands ###

