"""roles

Revision ID: 8f175f914ad6
Revises: 9b92a4bc2fe4
Create Date: 2025-04-25 08:35:12.931506+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f175f914ad6'
down_revision: Union[str, None] = '9b92a4bc2fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff_limits', sa.Column('feature_full_simple', sa.String(), nullable=True))

    op.execute("""
        UPDATE public.workspaces w
        SET max_concurrent_tasks = (
            SELECT tl.limit_value
            FROM public.tariff_limits tl
            WHERE tl.feature_name = 'max_concurrent_tasks'
              AND tl.tariff_id = w.tariff_id
            LIMIT 1
        )
        WHERE w.tariff_id IS NOT NULL and w.max_concurrent_tasks is null
    """)

    op.execute("""
        UPDATE public.roles
        SET role='admin', permission='{"endpoints": ["get_workspace_memberships_list", "get_case_by_external_id", "generate_case_from_record", "get_case_by_case_id",
        "get_project_by_id", "list_projects", "list_suites", "create_new_project", "create_new_suite", "create_new_case", "copy_case_by_case_id",
        "update_existing_project","update_existing_suite","change_suite_position",
        "update_existing_case","change_case_position","delete_existing_project","delete_existing_suite","delete_existing_case", "get_user_tree_route",
        "get_list_environments", "get_environments_by_id", "create_environment","update_environment","delete_environments",
        "happy_passes_list","happy_passes_full","happypass_autosop_generate","happypass_action_plan_update","delete_existing_happy_pass", "get_runs_tree_route",
        "get_run_by_id", "start_run_by_case_id", "stop_run_by_id", "create_group_run_by_cases", "update_group_run_case_untested", "delete_group_run_case_by_id",
        "group_run_case_tree", "start_run_by_group_run_id", "stop_run_by_group_run_id", "complete_run_cases_by_run_id","step_passed_run_case_by_run_id",
        "delete_cases_in_group_run", "invite_user", "edit_user_workspace_membership", "remove_user_workspace_membership",
        "get_free_streams_for_grouprun_by_project_id", "get_free_streams_for_active_workspace", "get_list_tariffs_limits_plan", "get_current_tariffs_limits_usage"]}'::json,
        description='Administrator'
        WHERE role='admin';
    """)

    op.execute("""
        UPDATE public.tariff_limits
        SET feature_full_simple = 'Test cases'

        WHERE feature_name = 'start_group_run'
    """)

    op.execute("""
        UPDATE public.tariff_limits
        SET feature_full_simple = 'Users'

        WHERE feature_name = 'invite_user_workspace'
    """)

    op.execute("""
        UPDATE public.tariff_limits
        SET feature_full_simple = 'Streams'

        WHERE feature_name = 'max_concurrent_tasks'
    """)

    op.execute("""
        UPDATE public.tariff_limits
        SET feature_full_simple = 'Recorder entries'

        WHERE feature_name = 'save_happy_pass'
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff_limits', 'feature_full_simple')
    # ### end Alembic commands ###
