"""idx

Revision ID: c1206b5d0c94
Revises: 81c050f07d10
Create Date: 2025-02-28 16:04:59.681634+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1206b5d0c94'
down_revision: Union[str, None] = '81c050f07d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_project_users_workspace_user', 'project_users', ['workspace_id', 'user_id'], unique=False)
    op.create_index('idx_project_id_name_description', 'projects', ['project_id', 'name', 'description'], unique=False)
    op.create_index('ix_workspace_id', 'projects', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_id', table_name='projects')
    op.drop_index('idx_project_id_name_description', table_name='projects')
    op.drop_index('idx_project_users_workspace_user', table_name='project_users')
    # ### end Alembic commands ###

