"""case_project_id

Revision ID: 079164942a43
Revises: 0c738f2135d1
Create Date: 2025-04-10 09:00:26.644934+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079164942a43'
down_revision: Union[str, None] = '0c738f2135d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_workspace_usage_last_reset', 'workspace_usage', ['last_reset'], unique=False)

    op.execute("""
        UPDATE public.cases a
        SET project_id = b.project_id
        FROM public.suites b
        WHERE a.suite_id = b.suite_id 
        AND a.project_id IS NULL;

    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workspace_usage_last_reset', table_name='workspace_usage')
    # ### end Alembic commands ###

