"""parallel group

Revision ID: 50d1a4e2be2e
Revises: 9fbc07f40094
Create Date: 2025-03-28 15:13:01.141418+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d1a4e2be2e'
down_revision: Union[str, None] = '9fbc07f40094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_run_cases', 'parallel_exec',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_run_cases', 'parallel_exec',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###

