"""avatar

Revision ID: 5076fe141e07
Revises: db1e6b81efa2
Create Date: 2025-03-07 18:54:14.100188+00:00

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5076fe141e07'
down_revision: Union[str, None] = 'db1e6b81efa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_memberships', 'avatar',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSON(),
               existing_nullable=True,
               postgresql_using='avatar::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_memberships', 'avatar',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###

