"""sorting

Revision ID: 2a5ddb44e981
Revises: ca82340b0b4d
Create Date: 2025-04-23 11:49:10.650835+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5ddb44e981'
down_revision: Union[str, None] = 'ca82340b0b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_run_cases', sa.Column('author', sa.String(), nullable=True))

    op.execute("""
        UPDATE public.group_run_cases a
        SET author = b.username
        FROM public.users b
        WHERE a.user_id = b.user_id
    """)


    op.create_index('idx_group_run_author', 'group_run_cases', ['author'], unique=False)
    op.create_index('idx_group_run_deadline', 'group_run_cases', ['deadline'], unique=False)
    op.create_index('idx_group_run_name', 'group_run_cases', ['name'], unique=False)
    op.create_index('idx_group_run_name_description', 'group_run_cases', ['name', 'description'], unique=False)
    op.create_index('idx_group_run_project_created', 'group_run_cases', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_group_run_project_status', 'group_run_cases', ['project_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_group_run_project_status', table_name='group_run_cases')
    op.drop_index('idx_group_run_project_created', table_name='group_run_cases')
    op.drop_index('idx_group_run_name_description', table_name='group_run_cases')
    op.drop_index('idx_group_run_name', table_name='group_run_cases')
    op.drop_index('idx_group_run_deadline', table_name='group_run_cases')
    op.drop_index('idx_group_run_author', table_name='group_run_cases')
    op.drop_column('group_run_cases', 'author')
    # ### end Alembic commands ###

