"""idx

Revision ID: db1e6b81efa2
Revises: 06200dc8e825
Create Date: 2025-03-06 15:52:07.815855+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1e6b81efa2'
down_revision: Union[str, None] = '06200dc8e825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_project_users_project_id', 'project_users', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_users_project_id', table_name='project_users')
    # ### end Alembic commands ###

