"""швч

Revision ID: 6cd3273af3c8
Revises: 6a381b8f56e1
Create Date: 2025-03-24 12:19:40.212948+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd3273af3c8'
down_revision: Union[str, None] = '6a381b8f56e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tariff_limits_tariff_id_feature_name', 'tariff_limits', ['tariff_id', 'feature_name'], unique=False)
    op.create_index('idx_workspace_usage_workspace_id_feature_name', 'workspace_usage', ['workspace_id', 'feature_name'], unique=False)

    op.execute("""
        UPDATE public.roles
        SET permission='{"endpoints": ["activate_or_renew_workspace","deactivate_workspace_now",
               "create_new_tariff","get_tariff_by_id","get_list_tariffs",
               "update_exist_tariff","delete_exist_tariff","create_new_tariff_limit",
               "get_tariff_limit_by_id","get_tariff_all_limits_by_tariff_id","update_exist_tariff_limit",
               "delete_exist_tariff_limit","list_users","check_user","block_user",
               "unlock_user", "change_renew_workspace_tariff"]}'::json
        WHERE role='system';
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workspace_usage_workspace_id_feature_name', table_name='workspace_usage')
    op.drop_index('idx_tariff_limits_tariff_id_feature_name', table_name='tariff_limits')
    # ### end Alembic commands ###

