"""idx

Revision ID: 0c738f2135d1
Revises: 50d1a4e2be2e
Create Date: 2025-03-31 09:23:56.366528+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c738f2135d1'
down_revision: Union[str, None] = '50d1a4e2be2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_run_cases_status_workspace_id', table_name='run_cases')
    op.create_index('idx_run_cases_group_run_id_status_workspace_id', 'run_cases', ['group_run_id', 'status', 'workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_run_cases_group_run_id_status_workspace_id', table_name='run_cases')
    op.create_index('idx_run_cases_status_workspace_id', 'run_cases', ['status', 'workspace_id'], unique=False)
    # ### end Alembic commands ###

