"""variables_membere

Revision ID: 94ce4a40384e
Revises: 722ed25b45ed
Create Date: 2025-08-21 13:54:01.848390+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94ce4a40384e'
down_revision: Union[str, None] = '722ed25b45ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flag_catalog', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'due_date'], unique=False)
    # ### end Alembic commands ###
    op.execute("""
        UPDATE public.roles
        SET role='member', permission='{"endpoints": ["get_workspace_memberships_list", "get_case_by_external_id", "get_case_by_case_id",
        "get_project_by_id", "list_projects", "list_suites", "create_new_suite", "create_new_case", "copy_case_by_case_id",
        "update_existing_suite","change_suite_position", "generate_case_from_record",
        "update_existing_case","change_case_position","delete_existing_suite","delete_existing_case", "get_user_tree_route",
        "get_list_environments", "get_environments_by_id", "create_environment","update_environment","delete_environments",
        "happy_passes_list","happy_passes_full","happypass_autosop_generate","happypass_action_plan_update","delete_existing_happy_pass", "get_runs_tree_route",
        "get_run_by_id", "start_run_by_case_id", "stop_run_by_id", "create_group_run_by_cases", "update_group_run_case_untested", "delete_group_run_case_by_id",
        "group_run_case_tree", "start_run_by_group_run_id", "stop_run_by_group_run_id", "complete_run_cases_by_run_id","step_passed_run_case_by_run_id",
        "delete_cases_in_group_run", "get_free_streams_for_grouprun_by_project_id", "get_list_variables_kit", "get_variables_kit_by_id","create_new_variables_kit",
        "update_variables_kit", "delete_variable_kit","get_list_variables_by_variables_kit_id","get_variable_by_id", "create_new_variable",
        "update_variables_kit","delete_variable_kit"]}'::json,
        description='Member'
        WHERE role='member';
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'last_check_at'], unique=False)
    op.alter_column('flag_catalog', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###

