"""extra

Revision ID: 69a6fff65034
Revises: 263bcf59c4b6
Create Date: 2025-04-28 13:06:08.478606+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a6fff65034'
down_revision: Union[str, None] = '263bcf59c4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_run_cases', sa.Column('extra', sa.String(), nullable=True))
    op.add_column('run_cases', sa.Column('extra', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_cases', 'extra')
    op.drop_column('group_run_cases', 'extra')
    # ### end Alembic commands ###

