"""mang

Revision ID: 0e305fa1b476
Revises: 7d2fc4b9ecfa
Create Date: 2025-03-12 15:18:15.293375+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e305fa1b476'
down_revision: Union[str, None] = '7d2fc4b9ecfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('happy_pass', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('happy_pass', 'language')
    # ### end Alembic commands ###

