"""idx

Revision ID: 2cbd65cd0bfe
Revises: 5076fe141e07
Create Date: 2025-03-07 20:21:41.756007+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbd65cd0bfe'
down_revision: Union[str, None] = '5076fe141e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_project_user_user_workspace', 'project_users', ['user_id', 'workspace_id'], unique=False)
    op.create_index('idx_workspace_membership_last_action_date', 'workspace_memberships', ['last_action_date'], unique=False)
    op.create_index('idx_workspace_membership_composite', 'workspace_memberships', ['workspace_id', 'role', 'status'], unique=False)
    op.create_index('idx_workspace_membership_workspace_id', 'workspace_memberships', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workspace_membership_workspace_id', table_name='workspace_memberships')
    op.drop_index('idx_workspace_membership_composite', table_name='workspace_memberships')
    op.drop_index('idx_project_users_workspace_user', table_name='workspace_memberships')
    op.drop_index('idx_project_user_user_workspace', table_name='project_users')
    # ### end Alembic commands ###

