"""new

Revision ID: d4403346d7b6
Revises: a94b62cc4598
Create Date: 2025-02-13 16:36:42.179417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4403346d7b6'
down_revision: Union[str, None] = 'a94b62cc4598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_run_case_cases', 'suite_name')
    op.drop_column('group_run_case_cases', 'position')
    op.drop_column('group_run_case_cases', 'suite_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_run_case_cases', sa.Column('suite_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('group_run_case_cases', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('group_run_case_cases', sa.Column('suite_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###

