"""position

Revision ID: 9da72a8751d4
Revises: 1e009daec6dd
Create Date: 2025-02-13 09:57:56.254803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da72a8751d4'
down_revision: Union[str, None] = '1e009daec6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('cases', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    op.create_index('ix_cases_position_suite_id', 'cases', ['position', 'suite_id'], unique=False)
    op.execute("UPDATE cases SET position = 0")
    op.alter_column('cases', 'position', server_default=None)

    op.add_column('suites', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    op.create_index('ix_suites_position_parent_id', 'suites', ['position', 'parent_id'], unique=False)
    op.execute("UPDATE suites SET position = 0")
    op.alter_column('suites', 'position', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suites_position_parent_id', table_name='suites')
    op.drop_column('suites', 'position')
    op.drop_index('ix_cases_position_suite_id', table_name='cases')
    op.drop_column('cases', 'position')
    # ### end Alembic commands ###

