"""attachments

Revision ID: 2fc00df71548
Revises: efd729b364fe
Create Date: 2025-02-21 10:43:23.712799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc00df71548'
down_revision: Union[str, None] = 'efd729b364fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_cases', sa.Column('attachments', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_cases', 'attachments')
    # ### end Alembic commands ###
