"""last_check

Revision ID: c7daac889938
Revises: 701b843af2e1
Create Date: 2025-05-14 09:28:31.716710+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7daac889938'
down_revision: Union[str, None] = '701b843af2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_history', sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'last_check_at'], unique=False)


    op.execute("""
        DELETE FROM public.payment_history
        WHERE last_check_at is null or corporate_invoice_flag is null ;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'due_date'], unique=False)
    op.drop_column('payment_history', 'last_check_at')
    # ### end Alembic commands ###
