"""case_type_in_run

Revision ID: 51df6e92b784
Revises: 545cbea126b9
Create Date: 2025-02-20 14:59:01.980642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51df6e92b784'
down_revision: Union[str, None] = '545cbea126b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('group_run_case_cases', sa.Column('case_type_in_run', sa.String(), nullable=False, server_default='automated'))
    op.execute("UPDATE group_run_case_cases SET case_type_in_run = 'automated'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_run_case_cases', 'case_type_in_run')
    # ### end Alembic commands ###
