"""happy_pass_workspace

Revision ID: 69d239f113fb
Revises: 121bfb1581f3
Create Date: 2025-03-06 13:00:31.185107+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '69d239f113fb'
down_revision: Union[str, None] = '121bfb1581f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Bind the current database session for raw SQL execution
bind = op.get_bind()
session = sa.orm.Session(bind=bind)

happy_pass_table = sa.Table(
    'happy_pass',
    sa.MetaData(),
    sa.Column('happy_pass_id', UUID),
    sa.Column('user_id', UUID),
    sa.Column('workspace_id', UUID)
)

users_table = sa.Table(
    'users',
    sa.MetaData(),
    sa.Column('user_id', UUID),
    sa.Column('active_workspace_id', UUID)
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('happy_pass', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'happy_pass', 'workspaces', ['workspace_id'], ['workspace_id'])

    # Select all happy pass entries
    happy_pass_entries = session.execute(sa.select(
        happy_pass_table.c.happy_pass_id,
        happy_pass_table.c.user_id
    )).fetchall()

    # Update each happy pass entry with the corresponding active workspace id
    for entry in happy_pass_entries:
        user_id = entry.user_id
        happy_pass_id = entry.happy_pass_id

        # Find the corresponding active_workspace_id for this user
        active_workspace_id = session.execute(
            sa.select(users_table.c.active_workspace_id).where(users_table.c.user_id == user_id)
        ).scalar()

        # Update the happy_pass record with the found active_workspace_id
        if active_workspace_id:
            session.execute(
                happy_pass_table.update().where(happy_pass_table.c.happy_pass_id == happy_pass_id).values(
                    workspace_id=active_workspace_id
                )
            )

    # Commit the session to save the changes
    session.commit()

# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'happy_pass', type_='foreignkey')
    op.drop_column('happy_pass', 'workspace_id')
    # ### end Alembic commands ###
