"""project_id

Revision ID: 545cbea126b9
Revises: 131192693be9
Create Date: 2025-02-17 10:27:03.877529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545cbea126b9'
down_revision: Union[str, None] = '131192693be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_run_cases', sa.Column('project_id', sa.UUID(), nullable=False))
    op.drop_index('idx_run_cases_group_case_created_at', table_name='run_cases')
    op.create_index('idx_run_cases_group_case_created_at', 'run_cases', ['group_run_id', 'case_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_run_cases_group_case_created_at', table_name='run_cases')
    op.create_index('idx_run_cases_group_case_created_at', 'run_cases', ['group_run_id', 'case_id', sa.text('created_at DESC')], unique=False)
    op.drop_column('group_run_cases', 'project_id')
    # ### end Alembic commands ###

