"""before_browser_default

Revision ID: 89e793fce384
Revises: fe1aab16e453
Create Date: 2025-07-22 07:27:17.272501+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e793fce384'
down_revision: Union[str, None] = 'fe1aab16e453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE cases SET before_browser_start = '[]' WHERE before_browser_start IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

