"""'parallel'

Revision ID: 50475df202ff
Revises: d4403346d7b6
Create Date: 2025-02-14 13:19:32.904860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50475df202ff'
down_revision: Union[str, None] = 'd4403346d7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_billing_transactions_user_id_amount', 'billing_transactions', ['user_id', 'amount'], unique=False)
    op.alter_column(
        'group_run_cases',
        'parallel_exec',
        existing_type=sa.BOOLEAN(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="parallel_exec::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_run_cases', 'parallel_exec',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_index('ix_billing_transactions_user_id_amount', table_name='billing_transactions')
    # ### end Alembic commands ###

