"""idx

Revision ID: eb8f5a2cc54b
Revises: c7daac889938
Create Date: 2025-05-14 14:23:16.019906+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8f5a2cc54b'
down_revision: Union[str, None] = 'c7daac889938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_history', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_history', 'email')
    # ### end Alembic commands ###

