"""threads

Revision ID: 491703660c22
Revises: b1ba83e58db8
Create Date: 2025-03-27 10:19:05.861960+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491703660c22'
down_revision: Union[str, None] = 'b1ba83e58db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_run_cases', sa.Column('use_parallel_flag', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('projects', sa.Column('parallel_exec', sa.Integer(), nullable=True, server_default='0'))

    # op.execute("""
    # UPDATE projects
    # SET parallel_exec = 0
    # """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'parallel_exec')
    op.drop_column('group_run_cases', 'use_parallel_flag')
    # ### end Alembic commands ###
