"""idx

Revision ID: b1ba83e58db8
Revises: 6136e587c35e
Create Date: 2025-03-26 10:35:15.195030+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ba83e58db8'
down_revision: Union[str, None] = '6136e587c35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_run_cases_status_workspace_id', 'run_cases', ['status', 'workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_run_cases_status_workspace_id', table_name='run_cases')
    # ### end Alembic commands ###

