"""update_case

Revision ID: d71df1be980f
Revises: eb8f5a2cc54b
Create Date: 2025-05-16 13:40:08.173023+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd71df1be980f'
down_revision: Union[str, None] = 'eb8f5a2cc54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'before_steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('cases', 'after_steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('cases', 'validation_steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'last_check_at'], unique=False)
    op.alter_column('cases', 'validation_steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('cases', 'after_steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('cases', 'before_steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###

