"""axtion_plan_id

Revision ID: e7ac34925e53
Revises: 40cc850f2592
Create Date: 2025-03-10 16:44:59.608230+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ac34925e53'
down_revision: Union[str, None] = '40cc850f2592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('action_plan_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'action_plan_id')
    # ### end Alembic commands ###

