"""environment in case

Revision ID: 011ab1ef28d8
Revises: 00372c3323d3
Create Date: 2025-11-19 09:14:33.230403+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '011ab1ef28d8'
down_revision: Union[str, None] = '00372c3323d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('cases', sa.Column('environment_id', sa.UUID(), nullable=True))
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'due_date'], unique=False)
    op.create_index('ix_payment_history_workspace_status_last_check_at', 'payment_history', ['status', 'last_check_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_workspace_status_last_check_at', table_name='payment_history')
    op.drop_index('ix_payment_history_workspace_status_due_date', table_name='payment_history')
    op.create_index('ix_payment_history_workspace_status_due_date', 'payment_history', ['status', 'last_check_at'], unique=False)
    op.drop_column('cases', 'environment_id')

    # ### end Alembic commands ###

