"""variables group run

Revision ID: 54c309661f64
Revises: eb5f63744ee3
Create Date: 2025-07-25 11:02:29.050611+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c309661f64'
down_revision: Union[str, None] = 'eb5f63744ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_run_cases', sa.Column('variables', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_run_cases', 'variables')
    # ### end Alembic commands ###

