"""shared_steps

Revision ID: 9532ef7c50f1
Revises: 2af958a8ee37
Create Date: 2025-10-10 09:47:27.491042+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9532ef7c50f1'
down_revision: Union[str, None] = '2af958a8ee37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_steps',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shared_steps_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_reason', sa.JSON(), nullable=False),
    sa.Column('action_plan', sa.JSON(), nullable=True),
    sa.Column('action_plan_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('shared_steps_id')
    )
    op.create_index('idx_shared_steps_shared_steps_id_project_id', 'shared_steps', ['shared_steps_id', 'project_id'], unique=False)
    op.create_index('ix_shared_steps_name_project_id', 'shared_steps', ['name', 'project_id'], unique=False)
    op.create_index('ix_shared_steps_project_id', 'shared_steps', ['project_id'], unique=False)
    op.create_table('case_shared_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('shared_steps_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_steps_id'], ['shared_steps.shared_steps_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_shared_steps_case_id', 'case_shared_steps', ['case_id'], unique=False)
    op.create_index('ix_case_shared_steps_shared_steps_id', 'case_shared_steps', ['shared_steps_id'], unique=False)
    op.add_column('cases', sa.Column('shared_steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'shared_steps')
    op.drop_index('ix_case_shared_steps_shared_steps_id', table_name='case_shared_steps')
    op.drop_index('ix_case_shared_steps_case_id', table_name='case_shared_steps')
    op.drop_table('case_shared_steps')
    op.drop_index('ix_shared_steps_project_id', table_name='shared_steps')
    op.drop_index('ix_shared_steps_name_project_id', table_name='shared_steps')
    op.drop_index('idx_shared_steps_shared_steps_id_project_id', table_name='shared_steps')
    op.drop_table('shared_steps')
    # ### end Alembic commands ###

