"""variables case param

Revision ID: c75a7774a6ad
Revises: 5eb7a02e21f9
Create Date: 2025-07-25 07:49:54.774721+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75a7774a6ad'
down_revision: Union[str, None] = '5eb7a02e21f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('variables', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'variables')
    # ### end Alembic commands ###

