"""external id uniq project

Revision ID: 7d2fc4b9ecfa
Revises: e7ac34925e53
Create Date: 2025-03-12 07:22:18.582393+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2fc4b9ecfa'
down_revision: Union[str, None] = 'e7ac34925e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cases_external_id_key', 'cases', type_='unique')
    op.create_unique_constraint('uc_case_external_id_project', 'cases', ['external_id', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_case_external_id_project', 'cases', type_='unique')
    op.create_unique_constraint('cases_external_id_key', 'cases', ['external_id'])
    # ### end Alembic commands ###

