"""швч

Revision ID: 0725be874f76
Revises: 80e1af53ff75
Create Date: 2025-04-14 11:12:36.882664+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0725be874f76'
down_revision: Union[str, None] = '80e1af53ff75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_log_entries_timestamp', 'log_entries', ['timestamp'], unique=False)
    op.create_index('ix_log_entries_workspace_id', 'log_entries', ['workspace_id'], unique=False)
    op.create_index('ix_log_entries_workspace_id_user_id', 'log_entries', ['workspace_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_log_entries_workspace_id_user_id', table_name='log_entries')
    op.drop_index('ix_log_entries_workspace_id', table_name='log_entries')
    op.drop_index('ix_log_entries_timestamp', table_name='log_entries')
    # ### end Alembic commands ###

