"""new tariff limit token

Revision ID: 8bf31708e39b
Revises: 4117f9115351
Create Date: 2026-02-12 08:29:33.932881+00:00

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from uuid import uuid4
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = '8bf31708e39b'
down_revision: Union[str, None] = '4117f9115351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tariff_limits_tariff_id_feature_name', table_name='tariff_limits')
    op.create_unique_constraint('uq_tariff_limits_tariff_feature', 'tariff_limits', ['tariff_id', 'feature_name'])
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    limits = {
        'starter': {
            'api_tokens': 0
        },
        'individual': {
            'api_tokens': 0
        },
        'corporate': {
            'api_tokens': 0
        },
        'team': {
            'api_tokens': -1
        }
    }
    # Insert data
    for tariff_name, features in limits.items():
        tariff_id_result = conn.execute(text("SELECT tariff_id FROM tariffs WHERE tariff_name = :tariff_name"), {"tariff_name": tariff_name}).fetchone()
        if tariff_id_result:
            tariff_id = tariff_id_result[0]
            for feature_name, limit_value in features.items():
                conn.execute(
                    text("""
                        INSERT INTO tariff_limits (limit_id, tariff_id, feature_name, limit_value)
                        VALUES (:limit_id, :tariff_id, :feature_name, :limit_value)
                        ON CONFLICT (tariff_id, feature_name) DO NOTHING
                    """),
                    {
                        "limit_id": str(uuid4()),
                        "tariff_id": tariff_id,
                        "feature_name": feature_name,
                        "limit_value": limit_value,
                    }
                )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        text("DELETE FROM tariff_limits where feature_name = 'api_tokens'")
    )
    op.drop_constraint('uq_tariff_limits_tariff_feature', 'tariff_limits', type_='unique')
    op.create_index('idx_tariff_limits_tariff_id_feature_name', 'tariff_limits', ['tariff_id', 'feature_name'], unique=False)

    # ### end Alembic commands ###
