"""100 max_concurrent_tasks

Revision ID: 982866ef4303
Revises: 23038a867eed
Create Date: 2026-03-03 06:35:12.201346+00:00

"""
from typing import Sequence, Union
from sqlalchemy.sql import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982866ef4303'
down_revision: Union[str, None] = '23038a867eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    tariff_id_result = conn.execute(text("SELECT tariff_id FROM public.tariffs WHERE tariff_name = 'corporate'")).fetchone()
    if tariff_id_result:
        tariff_id = tariff_id_result[0]

        conn.execute(text("UPDATE public.tariff_limits SET limit_value = 100, feature_full_name = '100 streams' WHERE feature_name = 'max_concurrent_tasks' and tariff_id = :tariff_id"),
                     {"tariff_id": tariff_id})

        conn.execute(text("UPDATE public.tariff_limits SET limit_value = -1 WHERE feature_name = 'api_tokens' and tariff_id = :tariff_id"),
                     {"tariff_id": tariff_id})

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    tariff_id_result = conn.execute(text("SELECT tariff_id FROM public.tariffs WHERE tariff_name = 'corporate'")).fetchone()
    if tariff_id_result:
        tariff_id = tariff_id_result[0]

        conn.execute(text("UPDATE public.tariff_limits SET limit_value = 100, feature_full_name = '100 streams' WHERE feature_name = 'max_concurrent_tasks' and tariff_id = :tariff_id"),
                     {"tariff_id": tariff_id})

        conn.execute(text("UPDATE public.tariff_limits SET limit_value = 0 WHERE feature_name = 'api_tokens' and tariff_id = :tariff_id"),
                     {"tariff_id": tariff_id})

    # ### end Alembic commands ###
