"""naming for feature api_tokens

Revision ID: 30ae63433a75
Revises: 8bf31708e39b
Create Date: 2026-02-12 08:36:36.673574+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ae63433a75'
down_revision: Union[str, None] = '8bf31708e39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE public.tariff_limits
        SET feature_full_simple = 'API tokens'
        WHERE feature_name = 'api_tokens'
        and feature_full_simple is NULL
    """)

    op.execute("""
        UPDATE public.tariff_limits
        SET feature_full_name = 'Unlimited API tokens'
        WHERE feature_name = 'api_tokens'
        and feature_full_name is NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
