"""new parallel exec

Revision ID: 102ad5402893
Revises: ddaf5bbdadb9
Create Date: 2026-02-17 13:31:24.473026+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102ad5402893'
down_revision: Union[str, None] = 'ddaf5bbdadb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_run_case_cases', sa.Column('execution_mode', sa.String(), nullable=True))
    op.add_column('group_run_case_cases', sa.Column('execution_order', sa.Integer(), nullable=True))
    op.create_index('idx_grcc_group_mode_order', 'group_run_case_cases', ['group_run_id', 'execution_mode', 'execution_order'], unique=False)

    op.add_column('group_run_cases', sa.Column('current_phase', sa.String(), nullable=True))
    op.add_column('group_run_cases', sa.Column('parallel_started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_group_run_project_phase_created', 'group_run_cases',
                    ['project_id', 'current_phase', 'created_at'], unique=False)

    op.add_column('run_cases', sa.Column('execution_mode', sa.String(), nullable=True))
    op.add_column('run_cases', sa.Column('execution_order', sa.Integer(), nullable=True))
    op.add_column('run_cases', sa.Column('case_type_in_run', sa.String(), nullable=True))

    op.create_index('idx_run_cases_group_mode_order_created', 'run_cases',
                    ['group_run_id', 'execution_mode', 'execution_order', 'created_at'], unique=False)
    op.create_index('idx_run_cases_group_mode_status_ws', 'run_cases',
                    ['group_run_id', 'execution_mode', 'status', 'workspace_id'], unique=False)

    # заполняем execution_mode в group_run_case_cases
    op.execute("""
        UPDATE group_run_case_cases grcc
        SET execution_mode = CASE WHEN grc.use_parallel_flag THEN 'parallel' ELSE 'sequential' END
        FROM group_run_cases grc
        WHERE grcc.group_run_id = grc.group_run_id
    """)

    # заполняем execution_order для sequential в group_run_case_cases по created_at в run_cases
    # если нет, то по ID
    op.execute("""
        WITH first_runs AS (
          SELECT
            grcc.id AS grcc_id,
            grcc.group_run_id,
            MIN(rc.created_at) AS first_created_at
          FROM group_run_case_cases grcc
          LEFT JOIN run_cases rc
            ON rc.group_run_case_id = grcc.id
               AND rc.group_run_id = grcc.group_run_id
          GROUP BY grcc.id, grcc.group_run_id
        ),
        ordered AS (
          SELECT
            fr.grcc_id,
            ROW_NUMBER() OVER (
              PARTITION BY fr.group_run_id
              ORDER BY fr.first_created_at NULLS LAST, fr.grcc_id
            ) AS rn
          FROM first_runs fr
          JOIN group_run_case_cases grcc ON grcc.id = fr.grcc_id
          WHERE grcc.execution_mode = 'sequential'
        )
        UPDATE group_run_case_cases grcc
        SET execution_order = ordered.rn
        FROM ordered
        WHERE grcc.id = ordered.grcc_id
    """)

    # заполняем аналогичные в run_cases
    op.execute("""
        UPDATE run_cases rc
        SET
          execution_mode = grcc.execution_mode,
          execution_order = grcc.execution_order
        FROM group_run_case_cases grcc
        WHERE rc.group_run_case_id = grcc.id
    """)

    op.execute("""
        UPDATE run_cases
        SET case_type_in_run = COALESCE(
        NULLIF(LOWER(current_case_version->>'case_type_in_run'), ''),
        NULLIF(LOWER(current_case_version->>'type'), ''),
        'automated'
        )
        WHERE case_type_in_run IS NULL;
    """)

    # после заполнения ставим поля обязательными
    op.execute("""
        UPDATE group_run_case_cases
        SET execution_mode = 'parallel'
        WHERE execution_mode IS NULL
    """)

    op.alter_column('group_run_case_cases', 'execution_mode', nullable=False)

    op.execute("""
        UPDATE run_cases
        SET case_type_in_run = 'automated'
        WHERE case_type_in_run IS NULL or group_run_id is null
    """)

    op.alter_column('run_cases', 'case_type_in_run', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_run_cases_group_mode_status_ws', table_name='run_cases')
    op.drop_index('idx_run_cases_group_mode_order_created', table_name='run_cases')
    op.drop_column('run_cases', 'case_type_in_run')
    op.drop_column('run_cases', 'execution_order')
    op.drop_column('run_cases', 'execution_mode')
    op.drop_index('idx_group_run_project_phase_created', table_name='group_run_cases')
    op.drop_column('group_run_cases', 'parallel_started_at')
    op.drop_column('group_run_cases', 'current_phase')
    op.drop_index('idx_grcc_group_mode_order', table_name='group_run_case_cases')
    op.drop_column('group_run_case_cases', 'execution_order')
    op.drop_column('group_run_case_cases', 'execution_mode')
    # ### end Alembic commands ###

