"""name in user_token

Revision ID: 0a4bfdf7b09b
Revises: 29bf1d6e0d5d
Create Date: 2026-02-11 13:26:39.410736+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4bfdf7b09b'
down_revision: Union[str, None] = '29bf1d6e0d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column("user_tokens", sa.Column("name", sa.String(), nullable=True))

    # Заполняем существующие записи на основе created_at
    op.execute("""
        UPDATE user_tokens
        SET name = 'BB_api_key_' ||
                   to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD_HH24-MI-SS')
        WHERE name IS NULL
    """)

    op.alter_column(
        "user_tokens",
        "name",
        existing_type=sa.String(),
        nullable=False
    )

    op.create_index(
        "ix_user_tokens_user_id_created_at",
        "user_tokens",
        ["user_id", "created_at"],
        unique=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tokens_user_id_created_at', table_name='user_tokens')
    op.drop_column('user_tokens', 'name')
    # ### end Alembic commands ###
