"""token_hash

Revision ID: 4117f9115351
Revises: 0a4bfdf7b09b
Create Date: 2026-02-12 07:01:10.693795+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '4117f9115351'
down_revision: Union[str, None] = '0a4bfdf7b09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    delete_query = text("""
        DELETE FROM user_tokens;
    """)
    conn.execute(delete_query)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('token_hash', sa.String(), nullable=False))
    op.drop_constraint('user_tokens_token_key', 'user_tokens', type_='unique')
    op.create_index(op.f('ix_user_tokens_token_hash'), 'user_tokens', ['token_hash'], unique=True)
    op.drop_column('user_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_tokens_token_hash'), table_name='user_tokens')
    op.create_unique_constraint('user_tokens_token_key', 'user_tokens', ['token'])
    op.drop_column('user_tokens', 'token_hash')
    # ### end Alembic commands ###
