"""'invitation_link'

Revision ID: d096d03c22cc
Revises: 982866ef4303
Create Date: 2026-03-03 08:46:41.227645+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd096d03c22cc'
down_revision: Union[str, None] = '982866ef4303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_memberships', sa.Column('invitation_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_memberships', 'invitation_link')
    # ### end Alembic commands ###

