"""indexes

Revision ID: a013095b4938
Revises: 102ad5402893
Create Date: 2026-02-24 13:10:27.209456+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a013095b4938'
down_revision: Union[str, None] = '102ad5402893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_group_run_updated_at', 'group_run_cases', ['updated_at'], unique=False)
    op.create_index('idx_run_cases_status_type_created', 'run_cases', ['status', 'case_type_in_run', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_run_cases_status_type_created', table_name='run_cases')
    op.drop_index('idx_group_run_updated_at', table_name='group_run_cases')
    # ### end Alembic commands ###

